name: Endor Labs - Java SCA Scan on Main Branch
on:
  workflow_dispatch
    
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: microsoft
            java-version: "17"

        - name: Compile Package
          run: mvn -f java/pom.xml clean install
            
        - name: Endor Labs SCA Scan
          uses: endorlabs/github-action@main
          with:
            namespace: "matt-demo"
            api: "https://api.endorlabs.com"
            pr: false
            enable_github_action_token: true
            scan_dependencies: true
            #scan_secrets: true
            #scan_git_logs: true
            additional_args: "--as-default-branch" #--tools --github --ghactions
            sarif_file: endor-labs.sarif
